/** Local image catalog — downloaded from the verified Unsplash pool
 *  into public/images/catalog (2026-06-12); no remote dependency remains.
 *  SmartImage still provides the branded fallback if a file goes missing. */
export const img = {
  heroTable: "/images/catalog/heroTable.jpg",
  banquetCandles: "/images/catalog/banquetCandles.jpg",
  weddingTent: "/images/catalog/weddingTent.jpg",
  weddingBallroom: "/images/catalog/weddingBallroom.jpg",
  weddingSweetheart: "/images/catalog/weddingSweetheart.jpg",
  weddingCouple: "/images/catalog/weddingCouple.jpg",
  weddingDance: "/images/catalog/weddingDance.jpg",
  weddingFlorals: "/images/catalog/weddingFlorals.jpg",
  weddingOutdoorArch: "/images/catalog/weddingOutdoorArch.jpg",
  longTableOutdoor: "/images/catalog/longTableOutdoor.jpg",
  corporateCrowd: "/images/catalog/corporateCrowd.jpg",
  galaSparklers: "/images/catalog/galaSparklers.jpg",
  galaLights: "/images/catalog/galaLights.jpg",
  dinnerToast: "/images/catalog/dinnerToast.jpg",
  partyToast: "/images/catalog/partyToast.jpg",
  dinnerOverhead: "/images/catalog/dinnerOverhead.jpg",
  platedFine: "/images/catalog/platedFine.jpg",
  platedOverhead: "/images/catalog/platedOverhead.jpg",
  steak: "/images/catalog/steak.jpg",
  ribs: "/images/catalog/ribs.jpg",
  dessertBerries: "/images/catalog/dessertBerries.jpg",
  saladBowl: "/images/catalog/saladBowl.jpg",
  tapasSpread: "/images/catalog/tapasSpread.jpg",
  rusticSpread: "/images/catalog/rusticSpread.jpg",
  mezzeOverhead: "/images/catalog/mezzeOverhead.jpg",
  minimalPlate: "/images/catalog/minimalPlate.jpg",
  bowl: "/images/catalog/bowl.jpg",
  buffetTrays: "/images/catalog/buffetTrays.jpg",
  cocktailsBar: "/images/catalog/cocktailsBar.jpg",
  cocktailsCheers: "/images/catalog/cocktailsCheers.jpg",
  cocktailPour: "/images/catalog/cocktailPour.jpg",
  cocktailCraft: "/images/catalog/cocktailCraft.jpg",
  chefSearing: "/images/catalog/chefSearing.jpg",
  chefPaella: "/images/catalog/chefPaella.jpg",
  chefTeam: "/images/catalog/chefTeam.jpg",
  chefWoman: "/images/catalog/chefWoman.jpg",
  chefKitchen: "/images/catalog/chefKitchen.jpg",
  chefHands: "/images/catalog/chefHands.jpg",
  kitchenScene: "/images/catalog/kitchenScene.jpg",
} as const;
